# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea40faba61d62913d6cb8fbd77a701d9511ef1ab4a3232607301fd2398902f5a9e1daf9ec47702e30c72824e6428cca6889332e080ed1181d7b784ba8d5238c

test:
  secret_key_base: 675fa66b30f8277ab39cdc46a5dc14c23b27c3dded2a5fdeee5a5afa468ebd688d4a056d21e8be1fdc10dd488052ea9c7454066b73b59ce3d0dde62c69e5d135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
