# Site wide configuration

title: 唤灵者的闲言碎语
description: 科技改变生活
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: 唤灵者
  email: me@xenonchau.com
  twitter: xenonchau
  google:
    ad-client: 
    ad-slot: 
  bio: coding
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: xenonchau

# Authors
data:
  authors:
    devtang:
      display_name: 唐巧
      gravatar: 60fd5218fff6927c0ed376cce01c5460
      email: 
      web: http://blog.devtang.com/
      twitter: 
      github: devtang
    onevcat:
      display_name: 王巍
      gravatar: 76dbcc74021b8039f14c7b583978b56d
      email: 
      web: http://www.onevcat.com/
      twitter: 
      github: onevcat


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
