### Site info:
title: 唤灵者的闲言碎语
tagline: 科技改变世界
author: XenonChau
name: 唤灵者
email: me@xenonchau.com
description: "文艺老青年的唠叨" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "iOS, 软件开发, cocos2d-x, NeuSoft"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.xenonchau.com" # the base hostname & protocol for your site


### Personal info and site tools info:
weibo_username: godtea
github_username:  xenonchau
disqus_shortname: xenonchau
douban_username: godtea
favicon:     "/images/favicon.ico"
aboutme: "我是唤灵者。iOS前端开发工程师，平时生性懒散，喜欢搞点未知领域的事情，但都浅尝辄止。" # these are shown on aboutme-sidebar.
aboutme_photo: "https://avatars2.githubusercontent.com/u/11521664?v=3&s=460" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "时光鸡"
      Blogroll: "博客链接"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "旧篇"
      Next: "新篇"
      PostedInCategories: "分类:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - author: devtang
      href: "http://blog.devtang.com/"
      name: "唐巧"
      title: "唐巧的技术博客 - 记录下自己学习的点滴"
    - author: onevcat
      href: "http://www.onevcat.com/"
      name: "王巍"
      title: "OneV's Den - 上善若水，人淡如菊"
    - author: lijiayu
      herf: "http://lijiayu.net/"
      name: "Lijia Yu"
      title: "On Your Mark - Never give up, Dream big"
    - author: cl0sure
      herf: "http://cl0sure.github.io/"
      name: "大翰"
      title: "大翰的Hexo"
    - author: iostang
      href: "http://iostang.github.io/"
      name: "汤勺"
      title: "唐先森的技术博客"
    - author: onery
      href: "http://www.oneryhandsome.com/"
      name: "应俊"
      title: "应俊的Jekyll"
    - author: whoiamwhere
      href: "http://www.whoiamwhere.com/"
      name: "小豪"
      title: "小豪的动感光波"
    - author: jiangxingfei
      href: "mailto:jiangxingfei@lanou3g.com"
      name: "老蒋"
      title: "给老蒋发邮件"


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
